-- Author: Rajkumar
-- Date: 2026-02-20
-- Description: Add BaseEntity columns to roles, auth_users, tokens tables

ALTER TABLE roles ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS modified_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE roles ADD COLUMN IF NOT EXISTS modified_by VARCHAR(255);
ALTER TABLE roles ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(255);

ALTER TABLE auth_users ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE auth_users ADD COLUMN IF NOT EXISTS modified_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE auth_users ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE auth_users ADD COLUMN IF NOT EXISTS modified_by VARCHAR(255);
ALTER TABLE auth_users ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(255);

ALTER TABLE tokens ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE tokens ADD COLUMN IF NOT EXISTS modified_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tokens ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE tokens ADD COLUMN IF NOT EXISTS modified_by VARCHAR(255);
ALTER TABLE tokens ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(255);
